apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-deployment-restart-role
  namespace: namepsace_of_restarting_service
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
